# frozen_string_literal: true

source 'http://rubygems.org'

gem 'icalendar'
gem 'rack'
gem 'sinatra'

group :test, :development do
  gem 'guard-rspec', require: false
  gem 'pry'
  gem 'rack-test'
  gem 'rspec'
end

group :development do
  gem 'reek', require: false
  gem 'rubocop', require: false
  gem 'rubycritic', require: false
end
